### PR TITLE
Add Sequence intent.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by radix** [comment]
Hey Tom, glad to see you're still interested in Effect :)

I can see how this offers something beyond manually chaining effects -- managing the list of results is pretty tedious in Python, but I have two questions:

1. practically, when do you want something like this?
2. do you understand [foldM][1]? I haven't grokked it myself, but I keep getting the feeling that maybe there is some useful combination of Effects with folds that is just beyond my understanding, and this is one of the situations that trigger that feeling. I haven't yet had the time to sit down and think about it for the requisite while, though.

[1]: http://hackage.haskell.org/package/base-4.8.0.0/docs/Control-Monad.html#v:foldM

**Comment by radix** [comment]
to @radix, for future reference: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.50.2961

**Comment by tomprince** [comment]
1. For the use case I have (https://github.com/ClusterHQ/flocker/pull/1267) I don't actually need the result. But I just need to run a bunch of things (in this case, remote SSH commands) in sequence.

2. Well, this is just [sequence](http://hackage.haskell.org/package/base-4.8.0.0/docs/Control-Monad.html#v:sequence). Haskell's `foldl` is just python's `reduce`; `foldM` is just the case where the reducing function has side-effects. I *think* sequence can be expressed in terms of `foldM`
``` haskell
sequence = foldM (\x y -> return (x ++ [y])) []
```
but I don't think that that is simpler.

**Comment by radix** [comment]
@tomprince

Could you check out #51 and #52?

I think this is a nicer formulation. Basically I just split up the "folding over effects" part of your PR from the "accumulating into a list" part. The error-handling is generalized to all folds, such that it raises a FoldError with the accumulator-so-far (not necessarily a list) and the original exception. I've also kept the optimization of appending to a list instead of concatenating lists.

I also dropped the intent. I can't think of a good reason to have an intent for it because tests would still just need to assert that each effect is performed in turn (usually with `SequenceDispatcher`).

**Comment by radix** [comment]
closing since #52 was merged. Thanks for the contribution.

**Pull request closed without merging**
