### PR TITLE
re-raise StopIteration unless it comes directly from the @do-wrapped generator

### PR DESCRIPTION
**Pull request by radix**
This is a fix for #36. There may be some edge cases I'm missing, so it'd be good if someone else can take a look.

### CODE REVIEW

**Comment by radix** [comment]
@glyph Since this is basically the exact same issue as https://twistedmatrix.com/trac/ticket/7767, I wonder if you have thought about any complexities preventing the simple solution from being acceptable.

That simple solution being: check if the traceback associated with the `StopIteration` has a `tb_next` that's not None, and if it is, reraise the exception. As far as I have observed, `StopIteration` raised from a `g.send()` never has more than one frame (the frame that's doing the call to `g.send()`) if they come directly from g.

Someone could apply the decorator to something other than a generator function -- say, something that wraps a generator function and alters its send behavior (or, perhaps more likely, something that "transparently" proxies all methods)? or an iterator? This would cause the code to mistakenly think that it's a "deeper" `StopIteration` exception and reraise it to the caller. I can't think of any cases where that's common/useful/interesting, and testing the function should immediately make it obvious that it won't work, since it'll raise StopIteration in all cases. So far this seems like an acceptable solution...

**Comment by cyli** [comment]
@radix That seems pretty reasonable to me - Maybe if you just document what *not* do to break it?  Like as a caveat?  (as you said, they shouldn't be doing it anyway...)

**Comment by radix** [comment]
Thanks @cyli! I'm gonna merge this once the build passes. The docstring was already saying you have to use it to wrap a generator function, but I added a little note that you can't wrap any other type of iterator, just to be extra clear. Thanks for looking it over :)

**Comment by glyph** [comment]
I've been thinking about this off and on since I was tagged, and the main thought I have is that it might be nice if this could be turned off for the obscure cases where it might break (instrumentation decorators, for example).

**Pull request merged**
