### PR TITLE
Test helper functions

### PR DESCRIPTION
**Pull request by manishtomar**
Some test related helper functions that we've been using in https://github.com/rackerlabs/otter/ for a long time.

### CODE REVIEW

**Comment by manishtomar** [comment]
@radix is it ok to drop 3.6 support? flake8 and sphinx not working.

**Comment by radix** [comment]
@manishtomar took me a bit to realize that you meant 2.6. I was like, wow, have I been gone from the Python world for that long!?

Anyway, given that Twisted no longer supports Python 2.6, I'm happy to have Effect drop support for it too. Go ahead and update the travis config to not run Python 2.6.

**Comment by radix** [comment]
... and the README too, please :)

**Comment by manishtomar** [comment]
@radix What are your thoughts on adding [`nested_sequence`](https://github.com/rackerlabs/otter/blob/master/otter/test/utils.py#L767) function here?

**Comment by radix** [comment]
@manishtomar That's fine. I'm not super happy with the function (the attrgetter part) but I can't really figure out anything better.

**Comment by manishtomar** [comment]
@radix review please.

**Comment by manishtomar** [comment]
@radix can you make a release? And maybe version it 0.11 since it has enhancements not a regression fix?

**Comment by radix** [comment]
@manishtomar done, thank you for the contributions :) https://github.com/python-effect/effect/releases/tag/0.11.0 && https://pypi.org/project/effect/

**Comment by manishtomar** [comment]
@radix Thanks for the upload! And please don't say thank you! This is still one of my fav packages and am constantly looking forward to using it in all new projects. Thank you so much for writing this :) I'll try to find time to make further contributions.

**Pull request merged**
